// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
        appId: '1:699008715686:web:dde4272ab5e2336ee15d67',
        messagingSenderId: '699008715686',
        projectId: 'albumlog-app-283ab',
        authDomain: 'albumlog-app-283ab.firebaseapp.com',
        storageBucket: 'albumlog-app-283ab.firebasestorage.app',
        measurementId: 'G-2710LHY4TJ',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
        appId: '1:699008715686:android:9c5589389deeb332e15d67',
        messagingSenderId: '699008715686',
        projectId: 'albumlog-app-283ab',
        storageBucket: 'albumlog-app-283ab.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
        appId: '1:699008715686:ios:8927c5758fa8c497e15d67',
        messagingSenderId: '699008715686',
        projectId: 'albumlog-app-283ab',
        storageBucket: 'albumlog-app-283ab.firebasestorage.app',
        iosBundleId: 'cl.javiermolina.buscaminas',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_MACOS'] ?? '',
        appId: '1:699008715686:ios:0bb862a287427e12e15d67',
        messagingSenderId: '699008715686',
        projectId: 'albumlog-app-283ab',
        storageBucket: 'albumlog-app-283ab.firebasestorage.app',
        iosBundleId: 'com.example.albumLog',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_WINDOWS'] ?? '',
        appId: '1:699008715686:web:e5b246a82d99e86ce15d67',
        messagingSenderId: '699008715686',
        projectId: 'albumlog-app-283ab',
        authDomain: 'albumlog-app-283ab.firebaseapp.com',
        storageBucket: 'albumlog-app-283ab.firebasestorage.app',
        measurementId: 'G-VTQT70YRQS',
      );
}